name: mrr_playbook
version: '1.0'
config-version: 2

require-dbt-version: ">=0.19.0"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
# seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

seeds:
  quote_columns: false
